// DO NOT EDIT!
// Automatically generated from docusaurus-template-liquid/templates/docusaurus.

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
{%- if topConfig.hasCli %}
import cliSidebar from "./sidebar-cli";
{%- endif %}
{%- if websiteConfig.hasTypedocApi %}
import typedocSidebarItems from "./docs/api/typedoc-sidebar.cjs";
{%- endif %}
{%- if websiteConfig.hasToolsSidebar %}
import toolsSidebar from './sidebars-tools.js';
{%- endif %}
{%- if websiteConfig.hasCustomGettingStartedSidebar %}
import {customDocsGettingStartedSidebarCategory} from "./sidebar-docs-getting-started-custom";
{%- endif %}
{%- if websiteConfig.hasCustomUserSidebar %}
import {customDocsUserSidebarCategory} from "./sidebar-docs-user-custom";
{%- endif %}
{%- if websiteConfig.hasCustomSidebar %}
import {customDocsSidebar} from "./sidebar-docs-custom";
{%- endif %}
{%- if websiteConfig.hasDoxygenDocusaurusApi %}
import doxygenSidebarItems from './sidebar-category-doxygen.json';
{%- elsif websiteConfig.hasTSDocDocusaurusApi %}
import tsdocSidebarItems from './sidebar-category-tsdoc.json';
{%- endif %}

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
{% if websiteConfig.hasCustomSidebar %}
  docsSidebar: customDocsSidebar,
{%- else %}
  docsSidebar: [
{%- if websiteConfig.hasCustomGettingStartedSidebar %}
    customDocsGettingStartedSidebarCategory,
{%- else %}
    {
      type: 'doc',
      id: 'getting-started/index',
      label: 'Getting Started'
    },
{%- endif %}
{%- if topConfig.isOrganisationWeb %}
    {
      type: 'doc',
      id: 'install/index',
      label: '{% if websiteConfig.customInstallLabel != "" %}{{websiteConfig.customInstallLabel}}{% else %}Installation Guides{% endif %}'
    },
    {
      type: 'doc',
      id: 'user/index',
      label: 'User\'s Guides'
    },
    {
      type: 'category',
      label: 'Contributor\'s Guides',
      link: {
        type: 'doc',
        id: 'developer/index',
      },
      items: [
        {
          type: 'doc',
          id: 'developer/install/prerequisites/index',
          label: 'Build Prerequisites'
        }
      ]
    },
    {
      type: 'doc',
      id: 'maintainer/index',
      label: 'Maintainer\'s Guides'
    },
    {
      type: 'doc',
      id: 'support/index',
      label: 'Help Centre'
    },
{%- else %}
{%- unless websiteConfig.skipInstallGuide %}
    {
      type: 'doc',
      id: 'install/index',
      label: '{% if websiteConfig.customInstallLabel != "" %}{{websiteConfig.customInstallLabel}}{% else %}Installation Guide{% endif %}'
    },
{%- endunless %}
{%- if websiteConfig.hasCustomUserSidebar %}
    customDocsUserSidebarCategory,
{%- else %}
    {
      type: 'doc',
      id: 'user/index',
      label: 'User\'s Guide'
    },
{%- endif %}
{%- unless websiteConfig.skipContributorGuide %}
    {
      type: 'doc',
      id: 'developer/index',
      label: 'Contributor\'s Guide'
    },
{%- endunless %}
{%- unless websiteConfig.skipMaintainerGuide %}
    {
      type: 'doc',
      id: 'maintainer/index',
      label: 'Maintainer\'s Guide'
    },
{%- endunless %}
{%- if topConfig.showTestsResults %}
    {
      type: 'doc',
      id: 'tests/index',
      label: 'Tests results'
    },
{%- endif %}
{%- unless packageWebsiteConfig.skipFaq %}
    {
      type: 'doc',
      id: 'faq/index',
      label: 'FAQ'
    },
{%- endunless %}
    {
      type: 'doc',
      id: 'support/index',
      label: 'Help Centre'
    },
{%- unless websiteConfig.skipReleases %}
    {
      type: 'doc',
      id: 'releases/index',
      label: 'Releases'
    },
{%- endunless %}
{%- endif %}
    {
      type: 'category',
      label: 'Project',
      link: {
        type: 'doc',
        id: 'project/about/index',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'project/about/index',
          label: 'About'
        },
        {
          type: 'doc',
          id: 'project/history/index',
          label: 'History'
        },
        {
          type: 'link',
          label: 'License',
          href: 'https://opensource.org/license/mit',
        },
      ]
    },
  ],
{%- endif %}

{%- if topConfig.showTestsResults %}

  testsSidebar: [{type: 'autogenerated', dirName: 'tests'}],
{%- endif %}

{%- if websiteConfig.hasToolsSidebar %}

  toolsSidebar,
{%- endif %}

{%- if websiteConfig.hasTypedocApi %}

  typedocSidebar: [
    {
      type: 'category',
      label: 'API Reference (TypeDoc)',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      collapsed: false,
      items: typedocSidebarItems,
    },
  ],
{%- endif %}

{%- if websiteConfig.hasDoxygenDocusaurusApi %}

  doxygenSidebar: [
    doxygenSidebarItems,
  ],

{%- elsif websiteConfig.hasTSDocDocusaurusApi %}

  tsdocSidebar: [
    tsdocSidebarItems,
  ],

{%- endif %}

{%- if topConfig.hasCli %}

  cliSidebar,
{%- endif %}
};

export default sidebars;
